[package]
name = "godwit-auth"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
godwit-core = { path = "../godwit-core" }
argon2 = { version = "0.6", features = ["std"] }
rand = "0.10"
bs58 = "0.5"
serde_json = { workspace = true }
jsonwebtoken = "9"
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
openidconnect = "3"
url = "2"
samael = "0.0.22"
aes-gcm = "0.11"
base64 = "0.23"
sha2 = "0.11"
hex = "0.4"
